// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RdpAudit.Core.Data;

#nullable disable

namespace RdpAudit.Core.Data.Migrations
{
	[DbContext(typeof(AuditDbContext))]
	[Migration("20260519152135_Stage2FirewallStats")]
	partial class Stage2FirewallStats
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

			modelBuilder.Entity("RdpAudit.Core.Models.AbuseReport", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<long?>("AlertId")
						.HasColumnType("INTEGER");

					b.Property<string>("Categories")
						.IsRequired()
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<string>("Error")
						.HasMaxLength(2048)
						.HasColumnType("TEXT");

					b.Property<string>("Ip")
						.IsRequired()
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<DateTime>("ReportedUtc")
						.HasColumnType("TEXT");

					b.Property<int>("ResponseCode")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.HasIndex("ReportedUtc");

					b.HasIndex("Ip", "ReportedUtc");

					b.ToTable("AbuseReports", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.ActiveBlock", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<DateTime>("CreatedUtc")
						.HasColumnType("TEXT");

					b.Property<DateTime?>("ExpiresUtc")
						.HasColumnType("TEXT");

					b.Property<string>("Ip")
						.IsRequired()
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<string>("LastError")
						.HasMaxLength(2048)
						.HasColumnType("TEXT");

					b.Property<int>("Provider")
						.HasColumnType("INTEGER");

					b.Property<string>("Reason")
						.IsRequired()
						.HasMaxLength(1024)
						.HasColumnType("TEXT");

					b.Property<string>("RuleHandle")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<int>("Status")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.HasIndex("ExpiresUtc");

					b.HasIndex("Status");

					b.HasIndex("Provider", "Ip")
						.IsUnique();

					b.HasIndex("Provider", "RuleHandle");

					b.ToTable("ActiveBlocks", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.Address", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("BlockReason")
						.HasMaxLength(512)
						.HasColumnType("TEXT");

					b.Property<int>("FailCount")
						.HasColumnType("INTEGER");

					b.Property<DateTime>("FirstSeen")
						.HasColumnType("TEXT");

					b.Property<string>("Ip")
						.IsRequired()
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<bool>("IsBlocked")
						.HasColumnType("INTEGER");

					b.Property<bool>("IsPublicIp")
						.HasColumnType("INTEGER");

					b.Property<DateTime>("LastSeen")
						.HasColumnType("TEXT");

					b.Property<int>("SuccessCount")
						.HasColumnType("INTEGER");

					b.Property<double>("ThreatScore")
						.HasColumnType("REAL");

					b.Property<string>("UserNames")
						.HasMaxLength(8192)
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("Ip")
						.IsUnique();

					b.HasIndex("IsBlocked");

					b.HasIndex("LastSeen");

					b.ToTable("Addresses", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.Alert", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<bool>("Acknowledged")
						.HasColumnType("INTEGER");

					b.Property<string>("Details")
						.HasMaxLength(65536)
						.HasColumnType("TEXT");

					b.Property<string>("Message")
						.IsRequired()
						.HasMaxLength(2048)
						.HasColumnType("TEXT");

					b.Property<string>("RuleId")
						.IsRequired()
						.HasMaxLength(64)
						.HasColumnType("TEXT");

					b.Property<int>("Severity")
						.HasColumnType("INTEGER");

					b.Property<string>("SourceIp")
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<DateTime>("TimeUtc")
						.HasColumnType("TEXT");

					b.Property<long>("TriggerEventId")
						.HasColumnType("INTEGER");

					b.Property<string>("UserName")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("Acknowledged");

					b.HasIndex("RuleId", "TimeUtc");

					b.HasIndex("TimeUtc", "Severity");

					b.ToTable("Alerts", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.AttackStat", b =>
				{
					b.Property<string>("Ip")
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<long>("DurationSeconds")
						.HasColumnType("INTEGER");

					b.Property<long>("Failed")
						.HasColumnType("INTEGER");

					b.Property<DateTime>("FirstSeenUtc")
						.HasColumnType("TEXT");

					b.Property<bool>("IsBlocked")
						.HasColumnType("INTEGER");

					b.Property<int?>("LastLoginType")
						.HasColumnType("INTEGER");

					b.Property<DateTime>("LastSeenUtc")
						.HasColumnType("TEXT");

					b.Property<DateTime>("LastUpdatedUtc")
						.HasColumnType("TEXT");

					b.Property<long>("Successful")
						.HasColumnType("INTEGER");

					b.Property<double>("ThreatScore")
						.HasColumnType("REAL");

					b.Property<string>("Top10AttemptedLogins")
						.IsRequired()
						.HasMaxLength(4096)
						.HasColumnType("TEXT");

					b.Property<long>("TotalAttempts")
						.HasColumnType("INTEGER");

					b.HasKey("Ip");

					b.HasIndex("IsBlocked");

					b.HasIndex("LastSeenUtc");

					b.HasIndex("ThreatScore");

					b.ToTable("AttackStats", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.BlocklistEntry", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<DateTime>("AddedUtc")
						.HasColumnType("TEXT");

					b.Property<DateTime?>("ExpiresUtc")
						.HasColumnType("TEXT");

					b.Property<string>("Ip")
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<bool>("IsEnabled")
						.HasColumnType("INTEGER");

					b.Property<long?>("LinkedAlertId")
						.HasColumnType("INTEGER");

					b.Property<string>("Login")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<string>("Reason")
						.IsRequired()
						.HasMaxLength(1024)
						.HasColumnType("TEXT");

					b.Property<int>("Source")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.HasIndex("ExpiresUtc");

					b.HasIndex("Ip");

					b.HasIndex("Login");

					b.HasIndex("IsEnabled", "ExpiresUtc");

					b.ToTable("BlocklistEntries", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.Bookmark", b =>
				{
					b.Property<string>("Channel")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<string>("BookmarkXml")
						.IsRequired()
						.HasMaxLength(8192)
						.HasColumnType("TEXT");

					b.Property<DateTime>("UpdatedUtc")
						.HasColumnType("TEXT");

					b.HasKey("Channel");

					b.ToTable("Bookmarks", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.DbProp", b =>
				{
					b.Property<string>("Key")
						.HasMaxLength(128)
						.HasColumnType("TEXT");

					b.Property<DateTime>("UpdatedUtc")
						.HasColumnType("TEXT");

					b.Property<string>("Value")
						.HasMaxLength(8192)
						.HasColumnType("TEXT");

					b.HasKey("Key");

					b.ToTable("DbProps", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.LoginRule", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<DateTime>("AddedUtc")
						.HasColumnType("TEXT");

					b.Property<bool>("Enabled")
						.HasColumnType("INTEGER");

					b.Property<string>("Login")
						.IsRequired()
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<string>("Note")
						.HasMaxLength(512)
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("Enabled");

					b.HasIndex("Login")
						.IsUnique();

					b.ToTable("LoginRules", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.RawEvent", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("AccessMask")
						.HasMaxLength(32)
						.HasColumnType("TEXT");

					b.Property<long?>("AddressId")
						.HasColumnType("INTEGER");

					b.Property<string>("AuthPackage")
						.HasMaxLength(64)
						.HasColumnType("TEXT");

					b.Property<string>("Channel")
						.IsRequired()
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<string>("CommandLine")
						.HasMaxLength(8192)
						.HasColumnType("TEXT");

					b.Property<string>("Details")
						.HasMaxLength(65536)
						.HasColumnType("TEXT");

					b.Property<string>("Domain")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<int>("EventId")
						.HasColumnType("INTEGER");

					b.Property<string>("LogonId")
						.HasMaxLength(32)
						.HasColumnType("TEXT");

					b.Property<int?>("LogonType")
						.HasColumnType("INTEGER");

					b.Property<string>("ObjectName")
						.HasMaxLength(1024)
						.HasColumnType("TEXT");

					b.Property<string>("ProcessName")
						.HasMaxLength(1024)
						.HasColumnType("TEXT");

					b.Property<bool>("Processed")
						.HasColumnType("INTEGER");

					b.Property<int?>("SessionId")
						.HasColumnType("INTEGER");

					b.Property<long?>("SessionRefId")
						.HasColumnType("INTEGER");

					b.Property<string>("SourceIp")
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<string>("Status")
						.HasMaxLength(64)
						.HasColumnType("TEXT");

					b.Property<DateTime>("TimeUtc")
						.HasColumnType("TEXT");

					b.Property<string>("UserName")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("AddressId");

					b.HasIndex("SessionRefId");

					b.HasIndex("EventId", "TimeUtc");

					b.HasIndex("LogonId", "TimeUtc");

					b.HasIndex("ObjectName", "EventId");

					b.HasIndex("Processed", "TimeUtc");

					b.HasIndex("SessionId", "TimeUtc");

					b.HasIndex("SourceIp", "TimeUtc");

					b.ToTable("RawEvents", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.Session", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<DateTime>("ConnectUtc")
						.HasColumnType("TEXT");

					b.Property<DateTime?>("DisconnectUtc")
						.HasColumnType("TEXT");

					b.Property<string>("Domain")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<string>("Flags")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<DateTime?>("LogoffUtc")
						.HasColumnType("TEXT");

					b.Property<string>("LogonId")
						.HasMaxLength(32)
						.HasColumnType("TEXT");

					b.Property<int?>("LogonType")
						.HasColumnType("INTEGER");

					b.Property<string>("SourceIp")
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<int>("Status")
						.HasColumnType("INTEGER");

					b.Property<string>("UserName")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<int>("WtsSessionId")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.HasIndex("Status");

					b.HasIndex("UserName", "ConnectUtc");

					b.HasIndex("WtsSessionId", "ConnectUtc");

					b.ToTable("Sessions", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.WhitelistEntry", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("AddedBy")
						.HasMaxLength(256)
						.HasColumnType("TEXT");

					b.Property<DateTime>("AddedUtc")
						.HasColumnType("TEXT");

					b.Property<string>("Ip")
						.IsRequired()
						.HasMaxLength(45)
						.HasColumnType("TEXT");

					b.Property<string>("Note")
						.HasMaxLength(512)
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("Ip")
						.IsUnique();

					b.ToTable("WhitelistEntries", (string)null);
				});

			modelBuilder.Entity("RdpAudit.Core.Models.RawEvent", b =>
				{
					b.HasOne("RdpAudit.Core.Models.Address", "Address")
						.WithMany()
						.HasForeignKey("AddressId")
						.OnDelete(DeleteBehavior.SetNull);

					b.HasOne("RdpAudit.Core.Models.Session", "SessionRef")
						.WithMany()
						.HasForeignKey("SessionRefId")
						.OnDelete(DeleteBehavior.SetNull);

					b.Navigation("Address");

					b.Navigation("SessionRef");
				});
#pragma warning restore 612, 618
		}
	}
}
